import * as React from 'react';
import { Card, CardContent, CardFooter, CardHeader, CardTitle } from '@/components/ui/card';
import { Sparkles } from 'lucide-react';
import { cn } from '@/lib/utils';

interface AISummaryCardProps {
  summary: string;
  className?: string;
}

/**
 * AISummaryCard Component
 *
 * Displays AI-generated summary in a card with:
 * - Icon and title indicating AI-generated content
 * - Well-formatted summary text with proper line breaks
 * - Footer indicating content is AI-generated
 *
 * Used in article detail page to display AI summary
 *
 * @example
 * <AISummaryCard summary={article.summary} />
 */
export function AISummaryCard({ summary, className }: AISummaryCardProps) {
  // Safe field access with fallback
  const summaryText = summary?.trim() || 'No summary available.';

  return (
    <Card
      className={cn('border-primary/20 bg-primary/5', className)}
      role="region"
      aria-label="AI Summary"
    >
      {/* Card Header with Icon */}
      <CardHeader>
        <CardTitle className="flex items-center gap-2 text-xl">
          <Sparkles className="h-5 w-5 text-primary" aria-hidden="true" />
          <span>AI Summary</span>
        </CardTitle>
      </CardHeader>

      {/* Summary Content */}
      <CardContent>
        <div className="prose prose-sm max-w-none dark:prose-invert">
          {summaryText === 'No summary available.' ? (
            <p className="text-muted-foreground italic">{summaryText}</p>
          ) : (
            <div className="whitespace-pre-wrap text-base leading-relaxed text-foreground">
              {summaryText}
            </div>
          )}
        </div>
      </CardContent>

      {/* Footer */}
      <CardFooter>
        <p className="text-xs text-muted-foreground">
          This summary was generated by AI and may not capture all nuances of the original article.
        </p>
      </CardFooter>
    </Card>
  );
}
