#!/usr/bin/env node
/**
 * generate-api - Generates TypeScript types from the backend Swagger spec.
 *
 * The backend (swaggo) emits Swagger 2.0, which openapi-typescript cannot
 * read directly, so the spec is converted to OpenAPI 3 first.
 *
 * Usage:
 *   node scripts/generate-api.mjs [spec]
 *
 *   spec: path or URL to the swagger doc (Swagger 2.0 or OpenAPI 3).
 *         Defaults to http://localhost:8080/swagger/doc.json
 *         (requires the backend to be running locally).
 *
 * Output: src/types/generated/api.d.ts
 *         Do not edit the output by hand. Friendly aliases for app code
 *         live in src/types/api.d.ts and derive from the generated file.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import converter from 'swagger2openapi';
import openapiTS, { astToString } from 'openapi-typescript';

const DEFAULT_SPEC = 'http://localhost:8080/swagger/doc.json';
const spec = process.argv[2] ?? process.env.SWAGGER_SPEC ?? DEFAULT_SPEC;

async function loadSpec(ref) {
  if (/^https?:\/\//.test(ref)) {
    const res = await fetch(ref);
    if (!res.ok) {
      throw new Error(`Failed to fetch ${ref}: HTTP ${res.status}`);
    }
    return res.json();
  }
  return JSON.parse(fs.readFileSync(ref, 'utf8'));
}

const raw = await loadSpec(spec);

/**
 * With `warnOnly: true`, swagger2openapi does not throw on recoverable
 * problems; it embeds each warning as an `x-s2o-warning` property at the
 * offending location. Surface them on stderr instead of silently
 * swallowing them.
 */
function reportConversionWarnings(node, pointer = '#') {
  if (node === null || typeof node !== 'object') {
    return;
  }
  for (const [key, value] of Object.entries(node)) {
    if (key === 'x-s2o-warning') {
      console.error(`[swagger2openapi] warning at ${pointer}: ${value}`);
    } else {
      reportConversionWarnings(value, `${pointer}/${key}`);
    }
  }
}

let openapi3 = raw;
if (raw.swagger === '2.0') {
  openapi3 = (await converter.convertObj(raw, { patch: true, warnOnly: true })).openapi;
  reportConversionWarnings(openapi3);
}

const ast = await openapiTS(openapi3);

const header = [
  '/* eslint-disable */',
  '/**',
  ' * AUTO-GENERATED by scripts/generate-api.mjs - DO NOT EDIT.',
  ' *',
  ' * Regenerate with: npm run generate:api [-- <path-or-url-to-swagger.json>]',
  ' */',
  '',
].join('\n');

const outPath = fileURLToPath(new URL('../src/types/generated/api.d.ts', import.meta.url));
fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, header + astToString(ast));
console.log(`Generated ${path.relative(process.cwd(), outPath)} from ${spec}`);
